spring.application.name=blog

jwt.secret=${JWT_SECRET:put-a-256-bits-jwt-key-here}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/name-of-your-database-schema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:your-username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your-password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
