spring.application.name=blog

jwt.secret=2cb3a5d915876926dd0a525099ae971784ae560c1ef13f0e4762beb1a346d297

spring.datasource.url=jdbc:postgresql://localhost:5432/postgresql
spring.datasource.username=postgres
spring.datasource.password=parigyan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect